#!/usr/bin/env bash

cd "$(dirname "$0")"

# Validate command line arguments
print_usage_and_exit() {
  echo "Usage: $0 [colorschemefilename.config]"
  echo
  exit
}
if [ $# -ne 1 ]; then
  print_usage_and_exit
fi

COLORSCHEME_FILENAME=$1

COLORSCHEME=`cat ${COLORSCHEME_FILENAME}`

cat > config <<EOF
###
### Autogenerated by $0 $@
### DO NOT EDIT THIS FILE BY HAND.
###

[options]
scroll_on_output = false
scroll_on_keystroke = true
audible_bell = false
mouse_autohide = false
allow_bold = true
dynamic_title = true
urgent_on_bell = true
clickable_url = true
font = Ubuntu Mono 12
scrollback_lines = 10000
search_wrap = true
#icon_name = terminal
#geometry = 640x480

# "system", "on" or "off"
cursor_blink = system

# "block", "underline" or "ibeam"
cursor_shape = block

# \$BROWSER is used by default if set, with xdg-open as a fallback
browser = xdg-open

# set size hints for the window
#size_hints = false

# Hide links that are no longer valid in url select overlay mode
filter_unmatched_urls = true

# emit escape sequences for extra modified keys
#modify_other_keys = false


[hints]
#font = Monospace 12
#foreground = #dcdccc
#background = #3f3f3f
#active_foreground = #e68080
#active_background = #3f3f3f
#padding = 2
#border = #3f3f3f
#border_width = 0.5
#roundness = 2.0

## The following was copied from ${COLORSCHEME_FILENAME}
${COLORSCHEME}
EOF
