#!/bin/bash
# 
# xmonad startup script. Intended to be run from an xsession configuration
# to run xmonad and some associated programs.
# 
# Author: David Brewer
# Repository: https://github.com/davidbrewer/xmonad-ubuntu-conf

#
# GENERAL INITIALIZATION
#

# Identify the home of our gtkrc file, important for setting styles of 
# gtk-based applications
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"

# Load X resources (fixes some font issues)
xrdb -merge .Xresources

#
# SCREEN CONFIGURATION
#

xrandr --output DVI-I-1 --auto --output DVI-D-0 --auto --right-of DVI-I-1 --output HDMI-0 --auto --right-of DVI-D-0

#
# STARTUP ICON TRAY
#

trayer \
  --edge top \
  --align right \
  --SetDockType true \
  --SetPartialStrut true \
  --expand true \
  --width 10 \
  --height 17 \
  --transparent true \
  --alpha 0 \
  --tint 0 \
&

# Run the gnome-keyring-daemon to avoid issues you otherwise may encounter
# when using gnome applications which expect access to the keyring, such
# as Empathy. This prevents prompts you may otherwise get for invalid
# certificates and the like.
gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh
# export SSH_AUTH_SOCK
# export GPG_AGENT_INFO

# On login, we unlock the ssh keychain so we're not prompted for 
# passphrases later. We pipe /dev/null to ssh-add to make it realize 
# it's not running in a terminal. Otherwise, it won't launch the prompt.
# 
# If you don't use the ssh keychain you may not want this. Commented
# by default as it is assumed many users will not want this feature.

# export SSH_ASKPASS="/usr/bin/ssh-askpass"
cat /dev/null | ssh-add &

# Remap caps lock to left control. This is not strictly speaking
# xmonad related, but it's handy if you're a vim user.
# setxkbmap -option 'ctrl:nocaps'

# Now, finally, start xmonad
exec xmonad