IgnorePath '/boot/*'
IgnorePath '/etc/.pwd.lock'
IgnorePath '/etc/.updated'
IgnorePath '/etc/NetworkManager/system-connections/*'
IgnorePath '/etc/adjtime'
IgnorePath '/etc/ca-certificates/extracted/*'
IgnorePath '/etc/cups/subscriptions.conf'
IgnorePath '/etc/dconf/db/ibus'
IgnorePath '/etc/dhcpcd.duid'
IgnorePath '/etc/dhcpcd.secret'
IgnorePath '/etc/docker/key.json' # https://stackoverflow.com/questions/47573820/what-is-etc-docker-key-json
IgnorePath '/etc/fstab'
IgnorePath '/etc/group'
IgnorePath '/etc/group-'
IgnorePath '/etc/gshadow'
IgnorePath '/etc/gshadow-'
IgnorePath '/etc/hostname'
IgnorePath '/etc/ld.so.cache' # "File containing an ordered list of libraries found in the directories specified in /etc/ld.so.conf, as well as those found in the trusted directories."
IgnorePath '/etc/machine-id' # https://wiki.debian.org/MachineId
IgnorePath '/etc/mkinitcpio.d/linux.preset' # https://wiki.archlinux.org/title/mkinitcpio#Automated_generation
IgnorePath '/etc/os-release' # This file (actually, symlink) is created by systemd. See https://bbs.archlinux.org/viewtopic.php?id=251724.
IgnorePath '/etc/pacman.d/gnupg/*' # keyring
IgnorePath '/etc/pacman.d/mirrorlist'
IgnorePath '/etc/passwd'
IgnorePath '/etc/passwd-'
IgnorePath '/etc/php56/*'
IgnorePath '/etc/printcap' # This file is automatically generated by cupsd.
IgnorePath '/etc/resolv.conf'
IgnorePath '/etc/resolv.conf.bak'
IgnorePath '/etc/shadow'
IgnorePath '/etc/shadow-'
IgnorePath '/etc/shells'
IgnorePath '/etc/ssh/ssh_host_*'
IgnorePath '/etc/ssl/certs/*'
IgnorePath '/etc/udev/rules.d/50-uhk60.rules'
IgnorePath '/etc/xml/catalog' # This comes from libxml2, which a number of packages depend on. http://xmlsoft.org/catalog.html
IgnorePath '/lost+found'
IgnorePath '/opt/containerd/*' # containerd likes to create this folder on startup. See https://github.com/containerd/containerd/blob/main/docs/managed-opt.md for more details.
IgnorePath '/usr/lib/displaylink/DLInstrumentationDirectoryLock'
IgnorePath '/usr/lib/ghc-*/package.conf.d/*.conf'
IgnorePath '/usr/lib/ghc-*/package.conf.d/package.cache'
IgnorePath '/usr/lib/graphviz/config6' # Autogenerated by `dot -c`: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=755065
IgnorePath '/usr/lib/locale/locale-archive' # https://man7.org/linux/man-pages/man1/localedef.1.html
IgnorePath '/usr/lib/modules/*'
IgnorePath '/usr/lib/node_modules/*'
IgnorePath '/usr/lib/python*/*'
IgnorePath '/usr/lib/ruby/*'
IgnorePath '/usr/lib/udev/hwdb.bin'  # https://www.freedesktop.org/software/systemd/man/hwdb.html
IgnorePath '/usr/lib/vlc/plugins/plugins.dat' # https://forums.debian.net/viewtopic.php?f=6&t=117859
IgnorePath '/usr/share/fonts/*'
IgnorePath '/usr/share/info/dir' # Index of all the info files. https://bbs.archlinux.org/viewtopic.php?id=55268
IgnorePath '/usr/share/nvim/runtime/lua/vim/lsp/handlers.lua' # Autogenerated
IgnorePath '/var/.updated' # https://www.freedesktop.org/software/systemd/man/systemd-update-done.service.html
IgnorePath '/var/lib/NetworkManager/*'
IgnorePath '/var/lib/alsa/asound.state'
IgnorePath '/var/lib/bluetooth/*'
IgnorePath '/var/lib/dbus/machine-id' # https://wiki.debian.org/MachineId
IgnorePath '/var/lib/dkms/*'
IgnorePath '/var/lib/docker/*'
IgnorePath '/var/lib/docker2/*'
IgnorePath '/var/lib/geoclue' # redshift depends on geoclue, which seems to be intent upon creating this folder.
IgnorePath '/var/lib/logrotate.status'
IgnorePath '/var/lib/machines' # https://www.freedesktop.org/software/systemd/man/machinectl.html
IgnorePath '/var/lib/mysql/*'
IgnorePath '/var/lib/pacman/local/*'
IgnorePath '/var/lib/pacman/sync/*'
IgnorePath '/var/lib/portables'  # Hard to find documented? https://bbs.archlinux.org/viewtopic.php?id=260291
IgnorePath '/var/lib/private' # https://bbs.archlinux.org/viewtopic.php?id=241818 and https://0pointer.net/blog/dynamic-users-with-systemd.html
IgnorePath '/var/lib/postgres/*'
IgnorePath '/var/lib/systemd/backlight/pci-0000:00:02.0:backlight:intel_backlight'
IgnorePath '/var/lib/systemd/backlight/platform-thinkpad_acpi:leds:tpacpi::kbd_backlight'
IgnorePath '/var/lib/systemd/catalog/database' # This file enumerates all logs including kernel, boot and application logs and provides required logs via journalctl utility. (https://itectec.com/ubuntu/ubuntu-where-are-all-the-major-log-files-located/)
IgnorePath '/var/lib/systemd/coredump/*'
IgnorePath '/var/lib/systemd/random-seed'
IgnorePath '/var/lib/systemd/rfkill/*'
IgnorePath '/var/lib/systemd/timers/stamp-*.timer' # systemd timer timestamps
IgnorePath '/var/lib/systemd/timesync/clock' # From https://wiki.archlinux.org/title/systemd-timesyncd: "The service writes to a local file /var/lib/systemd/timesync/clock with every synchronization. This location is hard-coded and cannot be changed. This may be problematic for running off read-only root partition or trying to minimize writes to an SD card."
IgnorePath '/var/lib/upower/history-*'
IgnorePath '/var/log/*'
IgnorePath '/var/spool/*'
IgnorePath '/var/tmp/*' # https://www.pathname.com/fhs/pub/fhs-2.3.html#VARTMPTEMPORARYFILESPRESERVEDBETWEE


### GTK
IgnorePath '/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache'
IgnorePath '/usr/lib/gtk-2.0/2.10.0/immodules.cache'
IgnorePath '/usr/lib/gtk-3.0/3.0.0/immodules.cache'
IgnorePath '/usr/lib/gio/modules/giomodule.cache'
IgnorePath '/usr/share/glib-2.0/schemas/gschemas.compiled' # https://developer.gnome.org/gio/stable/glib-compile-schemas.html

### Misc ignore
IgnorePath '/usr/share/applications/mimeinfo.cache' # https://specifications.freedesktop.org/desktop-entry-spec/0.9.5/ar01s07.html
IgnorePath '/usr/local/share/applications/mimeinfo.cache' # https://specifications.freedesktop.org/desktop-entry-spec/0.9.5/ar01s07.html
IgnorePath '/usr/share/mime/application/*'
IgnorePath '/usr/share/mime/*'
IgnorePath '/usr/share/icons/*/icon-theme.cache'

### Screenshots
#AddPackage screenkey # A screencast tool to display your keys inspired by Screenflick
#AddPackage byzanz # Record what's happening on your desktop
# TODO: get all this flameshot stuff into a package
IgnorePath '/usr/local/bin/flameshot'
IgnorePath '/usr/local/share/applications/flameshot.desktop'
IgnorePath '/usr/local/share/applications/org.flameshot.Flameshot.desktop'
IgnorePath '/usr/local/share/bash-completion/completions/flameshot'
IgnorePath '/usr/local/share/dbus-1/interfaces/org.dharkael.Flameshot.xml'
IgnorePath '/usr/local/share/dbus-1/interfaces/org.flameshot.Flameshot.xml'
IgnorePath '/usr/local/share/dbus-1/services/org.dharkael.Flameshot.service'
IgnorePath '/usr/local/share/dbus-1/services/org.flameshot.Flameshot.service'
IgnorePath '/usr/local/share/flameshot/*'
IgnorePath '/usr/local/share/icons/hicolor/128x128/apps/flameshot.png'
IgnorePath '/usr/local/share/icons/hicolor/128x128/apps/org.flameshot.Flameshot.png'
IgnorePath '/usr/local/share/icons/hicolor/48x48/apps/flameshot.png'
IgnorePath '/usr/local/share/icons/hicolor/48x48/apps/org.flameshot.Flameshot.png'
IgnorePath '/usr/local/share/icons/hicolor/scalable/apps/flameshot.svg'
IgnorePath '/usr/local/share/icons/hicolor/scalable/apps/org.flameshot.Flameshot.svg'
IgnorePath '/usr/local/share/metainfo/flameshot.appdata.xml'
IgnorePath '/usr/local/share/metainfo/org.flameshot.Flameshot.metainfo.xml'
IgnorePath '/usr/local/share/zsh/site-functions/_flameshot'

### volnoti
# TODO: get this into a package
# install_volnoti() {
#     # TODO: package this up in some useful way or find an alternative?
#     # Install [hcchu/volnoti](https://github.com/hcchu/volnoti#new-options-in-this-fork) from Github.
#     # [volnoti](https://aur.archlinux.org/packages/volnoti) doesn't have the features needed for volnoti-brightness.
#     if ! [ -x "$(command -v volnoti)" ]; then
#         (
#             mkdir -p ~/code/aur
#             cd ~/code/aur
#             rm -rf volnoti
#             git clone https://github.com/hcchu/volnoti.git
#             cd volnoti
#             ./prepare.sh
#             ./configure --prefix=/usr
#             (
#                 # See https://ubuntuforums.org/showthread.php?t=2215264&p=12978792#post12978792
#                 cd src;
#                 rm value-client-stub.h && make value-client-stub.h
#                 dbus-binding-tool --prefix=volume_object --mode=glib-client specs.xml > value-client-stub.h
#                 rm value-daemon-stub.h && make value-daemon-stub.h
#                 dbus-binding-tool --prefix=volume_object --mode=glib-server specs.xml > value-daemon-stub.h
#             )
#             make
#             sudo make install
#         )
#     fi
# }
IgnorePath '/usr/bin/volnoti'
IgnorePath '/usr/bin/volnoti-show'
IgnorePath '/usr/share/pixmaps/volnoti/display-brightness-symbolic.svg'
IgnorePath '/usr/share/pixmaps/volnoti/empty.png'
IgnorePath '/usr/share/pixmaps/volnoti/media-eject-symbolic.svg'
IgnorePath '/usr/share/pixmaps/volnoti/progressbar_empty.png'
IgnorePath '/usr/share/pixmaps/volnoti/progressbar_full.png'
IgnorePath '/usr/share/pixmaps/volnoti/volume_high.svg'
IgnorePath '/usr/share/pixmaps/volnoti/volume_low.svg'
IgnorePath '/usr/share/pixmaps/volnoti/volume_medium.svg'
IgnorePath '/usr/share/pixmaps/volnoti/volume_muted.svg'
IgnorePath '/usr/share/pixmaps/volnoti/volume_off.svg'
